[parity]
chain = "/config/chainspec.json"
no_persistent_txqueue = true
[rpc]
disable = false
port = 8545
interface = "0.0.0.0"
cors = ["all"]
apis = ["eth", "net", "parity"]
server_threads = 48
[websockets]
disable = true
[ipc]
disable = true
[secretstore]
disable = true
[network]
port = 30303
min_peers = 1
max_peers = 5
discovery = true
warp = false
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
reserved_peers = "/config/peers"
[footprint]
db_compaction = "ssd"
[snapshots]
enable = false
[account]
password = ["/config/password"]
